export const datas=[
    {
        id:43,
        name:"Estella",
        profile:"https://static.tutorialandexample.com/biography/parineeti-chopra1.png",
        lastMessage:"Okey",
        timeStamp:"07:59",
        isOnline:true,
        unreadCount:1
    },
    {
        id:15,
        name:"Cecelia",
        profile:"https://imagevars.gulfnews.com/2019/07/22/MS-Dhoni_16c1918e33b_large.jpg",
        lastMessage:"Done",
        timeStamp:"02:12",
        isOnline:false,
        unreadCount:0
    },
    {
        id:77,
        name:"Brent",
        profile:"https://static.tutorialandexample.com/biography/parineeti-chopra1.png",
        lastMessage:"have dinner?",
        timeStamp:"02:59",
        isOnline:true,
        unreadCount:0
    },
    {
        id:50,
        name:"Tillie",
        profile:"https://sportzwiki.com/wp-content/uploads/2021/01/Suresh-Raina-2.jpg",
        lastMessage:"Okey",
        timeStamp:"04:25",
        isOnline:true,
        unreadCount:0
    },
    {
        id:44,
        name:"Eunice",
        profile:"https://static.tutorialandexample.com/biography/parineeti-chopra1.png",
        lastMessage:"Okey",
        timeStamp:"09:59",
        isOnline:true,
        unreadCount:0
    },
    {
        id:11,
        name:"Kyle",
        profile:"https://odishabytes.com/wp-content/uploads/2020/10/shikhar-dhawan.jpg",
        lastMessage:"Okey",
        timeStamp:"07:59",
        isOnline:true,
        unreadCount:0
    },
    {
        id:12,
        name:"William",
        profile:"https://odishabytes.com/wp-content/uploads/2020/10/shikhar-dhawan.jpg",
        lastMessage:"Okey",
        timeStamp:"07:59",
        isOnline:true,
        unreadCount:0
    },
    {
        id:81,
        name:"Donald",
        profile:"https://odishabytes.com/wp-content/uploads/2020/10/shikhar-dhawan.jpg",
        lastMessage:"Okey",
        timeStamp:"07:59",
        isOnline:true,
        unreadCount:0
    },
    {
        id:14,
        name:"William",
        profile:"https://odishabytes.com/wp-content/uploads/2020/10/shikhar-dhawan.jpg",
        lastMessage:"Okey",
        timeStamp:"07:59",
        isOnline:true,
        unreadCount:0
    },
    {
        id:99,
        name:"Donald",
        profile:"https://odishabytes.com/wp-content/uploads/2020/10/shikhar-dhawan.jpg",
        lastMessage:"Okey",
        timeStamp:"07:59",
        isOnline:true,
        unreadCount:0
    },
    {
        id:169,
        name:"William",
        profile:"https://odishabytes.com/wp-content/uploads/2020/10/shikhar-dhawan.jpg",
        lastMessage:"Okey",
        timeStamp:"07:59",
        isOnline:true,
        unreadCount:0
    },
    {
        id:105,
        name:"Donald",
        profile:"https://odishabytes.com/wp-content/uploads/2020/10/shikhar-dhawan.jpg",
        lastMessage:"Okey",
        timeStamp:"07:59",
        isOnline:true,
        unreadCount:0
    },
    {
        id:999,
        name:"William",
        profile:"https://odishabytes.com/wp-content/uploads/2020/10/shikhar-dhawan.jpg",
        lastMessage:"Okey",
        timeStamp:"07:59",
        isOnline:true,
        unreadCount:0
    },
    {
        id:102,
        name:"Donald",
        profile:"https://odishabytes.com/wp-content/uploads/2020/10/shikhar-dhawan.jpg",
        lastMessage:"Okey",
        timeStamp:"07:59",
        isOnline:true,
        unreadCount:0
    },
    {
        id:1662,
        name:"William",
        profile:"https://odishabytes.com/wp-content/uploads/2020/10/shikhar-dhawan.jpg",
        lastMessage:"Okey",
        timeStamp:"07:59",
        isOnline:true,
        unreadCount:0
    },
    {
        id:206,
        name:"Donald",
        profile:"https://odishabytes.com/wp-content/uploads/2020/10/shikhar-dhawan.jpg",
        lastMessage:"Okey",
        timeStamp:"07:59",
        isOnline:true,
        unreadCount:0
    },
]